version: '3.4'

services:
  db:
    image: postgres:9.4.1
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  puma:
    build: .
    image: puma
    command: bash -c 'rm -f tmp/pids/server.pid && bundle exec rails server'
    #command: bin/rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/src
volumes:
  gem_cache:
  db_data:
  node_modules: 