# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000



# development: &default
#   adapter: ENV["DB_ADAPTER"]
#   database: ENV["DB"]
#   min_messages: ENV["DB_MIN_MESSAGES"]
#   pool: ENV["DB_POOL"]
#   username: ENV["DB_USERNAME"]
#   host: ENV["DB_HOST"]

development: &default
  adapter: postgresql
  database: backbone_data_bootstrap_development
  min_messages: WARNING
  pool: 5
  username: postgres
  host: db

test:
  <<: *default
  database: backbone_data_bootstrap_test

production:
  <<: *default
  database: db/production.sqlite3
