default: &default
  adapter: <%= ENV["DB_ADAPTER"] %>
  database: <%= ENV["DB"] %>
  min_messages: <%= ENV["DB_MIN_MESSAGES"] %>
  pool: <%= ENV["DB_POOL"] %>
  username: <%= ENV["DB_USERNAME"] %>
  host: <%= ENV["DB_HOST"] %>
  timeout: 5000

development: 
  <<: *default

test:
  <<: *default

production:
  <<: *default
